# Generated by Django 3.1 on 2020-08-17 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Interaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('input_value', models.CharField(max_length=100)),
                ('output', models.TextField()),
                ('script', models.TextField()),
                ('active', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'interaction',
            },
        ),
    ]
